[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "Beyond The Borders - Legacy Edition"
authors = [{name = "TheDailyXPerience", email = ""}]
dynamic = ["version", "description"]
